export var reviews = [
    {name:"Gábor Gábor", body:"Ez a termék egyszerűen fantasztikus! Mindent tud, amit ígér.", time:"2004.09.10 10:50"},
    {name:"Anna Anikó", body:"Nem gondoltam volna, hogy ilyen jól fog működni. Nagyon meg vagyok elégedve.", time:"2004.09.10 10:50"},
    {name:"Béla Bálint", body:"Hát, őszintén szólva, nem értem, miért olyan nagy szám ez. Nem volt különösebben jó.", time:"2004.09.10 10:50"},
    {name:"Péter Pál", body:"Elképesztő! Mindenki ezt használja, és most már értem miért.", time:"2004.09.10 10:50"},
    {name:"József János", body:"Kétségbeejtően gyenge minőség. Alig használtam, és már elromlott.", time:"2004.09.10 10:50"},
    {name:"Kata Kati", body:"Eddig a legjobb vásárlásom volt. Nem is tudom, hogy eddig miért nem vettem meg.", time:"2004.09.10 10:50"},
    {name:"Dávid Dávid", body:"Valószínűleg a legjobb döntésem volt, hogy megvettem. Megéri minden egyes fillért.", time:"2004.09.10 10:50"},
    {name:"László László", body:"Szinte minden rendben volt, de a kiszállítás katasztrófa volt. Két napig vártam, hogy megérkezzen.", time:"2004.09.10 10:50"},
    {name:"Zoltán Zoli", body:"Nem ajánlom senkinek. A termék nem működött, ahogy azt ígérték.", time:"2004.09.10 10:50"},
    {name:"Erika Erzsébet", body:"Egy szép darab. De a doboza kicsit megsérült a szállítás közben.", time:"2004.09.10 10:50"},
    {name:"Miklós Miklós", body:"Hogy őszinte legyek, egyáltalán nem tetszik. Sokkal jobban teljesítenek a konkurens termékek.", time:"2004.09.10 10:50"},
    {name:"Vera Veronika", body:"Minden rendben volt, nagyon gyors szállítás, a termék szuper.", time:"2004.09.10 10:50"},
    {name:"Tamás Tamás", body:"Nem akartam elhinni, de tényleg igaz, amit mondanak róla! Egyszerűen zseniális.", time:"2004.09.10 10:50"},
    {name:"Ádám Ádám", body:"Az ár-érték arány megfelelő, de nem hozta azt a szintet, amit vártam.", time:"2004.09.10 10:50"},
    {name:"Lilla Lilla", body:"Minden szuper, csak egy kis bibi, hogy a telefonálás közben néha elveszti a jelet.", time:"2004.09.10 10:50"},
    {name:"Balázs Balázs", body:"Nagyon csalódtam. A leírás és a valóság köszönő viszonyban sincs egymással.", time:"2004.09.10 10:50"},
    {name:"Rita Réka", body:"Meglepően jól teljesít. Biztosan ajánlani fogom másoknak is.", time:"2004.09.10 10:50"},
    {name:"Gergő Gergő", body:"Nem éri meg az árát. Az első pár használat után már meg is javítottam.", time:"2004.09.10 10:50"},
    {name:"László László", body:"Tökéletes, mint mindig. Imádom!", time:"2004.09.10 10:50"}
];